# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLetter', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HRemail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=200)),
                ('positionDescription', models.CharField(max_length=2000)),
                ('educationLevel', models.CharField(max_length=20)),
                ('experienceLevel', models.CharField(max_length=20)),
                ('experienceField', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=24)),
                ('lastName', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Postings'),
        ),
        migrations.AddField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.User'),
        ),
    ]
