# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='educationField',
            field=models.CharField(default='My Field', max_length=20),
        ),
        migrations.AlterField(
            model_name='postings',
            name='experienceField',
            field=models.CharField(default='My Field', max_length=20),
        ),
        migrations.AlterField(
            model_name='postings',
            name='experienceLevel',
            field=models.IntegerField(default=0),
        ),
    ]
